name: Daily Movie Update
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at Midnight
  workflow_dispatch:   # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Update Script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          UNIVERSAL_LINK: ${{ secrets.UNIVERSAL_LINK }}
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "MovieBot"
          git config --global user.email "bot@github.com"
          git add index.html
          git commit -m "Automated Movie Update"
          git push
